# Generated by Django 6.0.5 on 2026-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_empleado',
            field=models.CharField(blank=True, help_text='Código único de empleado (ej: EMP-0001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarjeta_expiry',
            field=models.CharField(blank=True, help_text='Caducidad MM/AA', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarjeta_numero',
            field=models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta guardada', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tarjeta_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('guardada', 'Tarjeta guardada'), ('nueva', 'Tarjeta nueva'), ('saldo', 'Saldo'), ('efectivo', 'Efectivo')], max_length=20),
        ),
    ]
