# Generated by Django 6.0.5 on 2026-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_usuario_id_empleado_usuario_tarjeta_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('redsys', 'Redsys TPV'), ('tarjeta', 'Tarjeta'), ('guardada', 'Tarjeta guardada'), ('nueva', 'Tarjeta nueva'), ('saldo', 'Saldo'), ('efectivo', 'Efectivo')], max_length=20),
        ),
    ]
